"""Regenerate public/visualization/data.js from data/titanic_raw.csv.

Run with Miniconda's python — the python on PATH on this machine cannot import
pandas:

    C:/Users/kangc/Miniconda3/python.exe build_data.py

The CSV lives in this folder on purpose, so the site can be rebuilt without the
course repository being present.
"""
import json
import pathlib

import pandas as pd

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE / "data" / "titanic_raw.csv"
OUT = HERE / "public" / "visualization" / "data.js"

t = pd.read_csv(SRC)
cols = ["PassengerId", "Survived", "Pclass", "Name", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"]
rows = []
for r in t[cols].itertuples(index=False):
    d = list(r)
    d[5] = None if pd.isna(d[5]) else float(d[5])
    d[9] = None if pd.isna(d[9]) else d[9]
    d[8] = round(float(d[8]), 4)
    rows.append(d)
OUT.write_text("// Kaggle Titanic train.csv, 891 rows. Generated by build_data.py - do not edit.\n"
               "window.TITANIC_COLS = " + json.dumps(cols) + ";\n"
               "window.TITANIC = " + json.dumps(rows, ensure_ascii=False) + ";\n", encoding="utf-8")
print(len(rows), "rows ->", OUT)
