"""Regenerate public/visualization/data.js from the Week 3 Titanic CSV.
Run with Miniconda's python (see HANDOFF.md section 1)."""
import json, pathlib
import pandas as pd

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "Lectures/Week03/wk_3_code/data/titanic_raw.csv"
OUT = pathlib.Path(__file__).parent / "public/visualization/data.js"

t = pd.read_csv(SRC)
cols = ["PassengerId", "Survived", "Pclass", "Name", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"]
rows = []
for r in t[cols].itertuples(index=False):
    d = list(r)
    d[5] = None if pd.isna(d[5]) else float(d[5])
    d[9] = None if pd.isna(d[9]) else d[9]
    d[8] = round(float(d[8]), 4)
    rows.append(d)
OUT.write_text("// Kaggle Titanic train.csv, 891 rows. Generated by build_data.py - do not edit.\n"
               "window.TITANIC_COLS = " + json.dumps(cols) + ";\n"
               "window.TITANIC = " + json.dumps(rows, ensure_ascii=False) + ";\n", encoding="utf-8")
print(len(rows), "rows ->", OUT)
